task:
  name: FreeBSD # https://www.freebsd.org/releases
  freebsd_instance: # https://cirrus-ci.org/guide/FreeBSD/#list-of-available-image-families
    matrix:
      image_family: freebsd-13-4
      image_family: freebsd-14-2
  env:
    IGNORE_OSVERSION: yes # supress package installation error on FreeBSD-13

  install_script:
    - pkg update -f
    - sudo pkg install -y bash

  build_script:
    - bash ./scripts/build_libcpuid.sh
    - bash ./scripts/build_cpu_x.sh -s "$(realpath .)"

  run_script:
    - sudo CPUX_BCLK=100 cpu-x --issue-fmt
    - cat /tmp/cpu-x.log
    - cat /tmp/cpu-x-daemon.log
