name: AppImage Continuous

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  linux-appimage-continuous:
    name: Linux x64_64 (Continuous)
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - uses: abbbi/github-actions-tune@v1

    - name: Build libcpuid
      run: bash -x ./scripts/build_libcpuid.sh "$BUILD_TYPE"

    - name: Build CPU-X
      run: bash -x ./scripts/build_cpu_x.sh "$BUILD_TYPE" "$GITHUB_WORKSPACE" "$GITHUB_WORKSPACE/AppDir"

    - name: Package CPU-X as an AppImage
      run: bash -x ./scripts/build_appimage.sh "$GITHUB_WORKSPACE" "$GITHUB_WORKSPACE/AppDir"

    - name: Delete previous continuous release
      uses: dev-drprasad/delete-tag-and-release@v1.1
      with:
        tag_name: continuous
        delete_release: true
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create continuous release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "AppImage/CPU-X-*.AppImage*"
        body: |
          :heavy_check_mark:CPU-X AppImage built from latest commit ([${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})). See [known issues](https://github.com/TheTumultuousUnicornOfDarkness/CPU-X/wiki/appimage).

          :scroll: Build log: https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks?check_suite_id=${{ github.run_id }}
        commit: ${{ github.sha }}
        draft: false
        name: Continuous build
        prerelease: true
        removeArtifacts: true
        replacesArtifacts: true
        skipIfReleaseExists: false
        tag: continuous
        token: "${{ secrets.GITHUB_TOKEN }}"
