name: AppImage Versioned

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  linux-appimage-versioned-build:
    name: Linux ${{ matrix.os.arch }} (Versioned build)
    runs-on: ${{ matrix.os.label }}
    strategy:
      matrix:
        os:
          # x86_64 (https://github.com/actions/runner-images/tree/main/images/ubuntu)
          - { arch: x86_64, label: ubuntu-22.04 }
          # ARM64 (https://github.com/actions/partner-runner-images)
          - { arch: aarch64, label: ubuntu-22.04-arm }

    steps:
    - uses: actions/checkout@v4

    - uses: abbbi/github-actions-tune@v1

    - name: Set environment variables
      run: |
        echo "VERSION=${GITHUB_REF_NAME/v/}" >> $GITHUB_ENV
        echo "CHANGELOG_TAG=${GITHUB_REF_NAME//./}---$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Build libcpuid
      run: bash -x ./scripts/build_libcpuid.sh "$BUILD_TYPE"

    - name: Build CPU-X
      run: bash -x ./scripts/build_cpu_x.sh "$BUILD_TYPE" "$GITHUB_WORKSPACE" "$GITHUB_WORKSPACE/AppDir"

    - name: Package CPU-X as an AppImage
      run: bash -x ./scripts/build_appimage.sh "$GITHUB_WORKSPACE" "$GITHUB_WORKSPACE/AppDir"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-${{ matrix.os.arch }}
        path: AppImage/CPU-X-${{ matrix.os.arch }}.AppImage*


  linux-appimage-versioned-release:
    name: Linux (Versioned release)
    runs-on: ubuntu-latest

    steps:
    - name: Download Linux AArch64 artifacts
      uses: dawidd6/action-download-artifact@v6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit: ${{ github.sha }}
        name: linux-aarch64
        path: AppImage/

    - name: Download Linux x86_64 artifacts
      uses: dawidd6/action-download-artifact@v6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit: ${{ github.sha }}
        name: linux-x86_64

    - name: Create versioned release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: false
        artifacts: "AppImage/CPU-X-*.AppImage*"
        body: |
          **Version ${{ env.VERSION }}.**

          [ChangeLog](https://github.com/TheTumultuousUnicornOfDarkness/CPU-X/blob/master/ChangeLog.md#${{ env.CHANGELOG_TAG }})

          ## Packages

          Search the `cpu-x` package in your repositories or [CPU-X on Flathub](https://flathub.org/fr/apps/io.github.thetumultuousunicornofdarkness.cpu-x).

          ## Binary

          - **AppImage (ARM64)**: CPU-X-v${{ env.VERSION }}-aarch64.AppImage (**libfuse2** package is required)
          - **AppImage (x86_64)**: CPU-X-v${{ env.VERSION }}-x86_64.AppImage (**libfuse2** package is required)

          *Note: a Polkit Authentication agent is mandatory to start daemon from GUI.*

          ## Notes

          ### To packagers
          -

          ### To users
          -
        commit: ${{ github.sha }}
        draft: true
        name: ${{ github.ref_name }}
        prerelease: false
        replacesArtifacts: true
        skipIfReleaseExists: true
        tag: ${{ github.ref_name }}
        token: "${{ secrets.GITHUB_TOKEN }}"
