name: Linux build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  linux-build:
    name: Linux ${{ matrix.os.arch }} (Build)
    runs-on: ${{ matrix.os.label }}
    strategy:
      matrix:
        os:
          # x86_64 (https://github.com/actions/runner-images/tree/main/images/ubuntu)
          - { arch: x86_64, label: ubuntu-22.04 }
          - { arch: x86_64, label: ubuntu-24.04 }
          # ARM64 (https://github.com/actions/partner-runner-images)
          - { arch: aarch64, label: ubuntu-22.04-arm }
          - { arch: aarch64, label: ubuntu-24.04-arm }

    steps:
    - uses: actions/checkout@v4

    - uses: abbbi/github-actions-tune@v1

    - name: Install prerequisites
      run: sudo apt-get update -y -qq

    - name: Build libcpuid
      run: ./scripts/build_libcpuid.sh -t "$BUILD_TYPE"

    - name: Build CPU-X
      run: ./scripts/build_cpu_x.sh -s "$GITHUB_WORKSPACE" -t "$BUILD_TYPE"

    - name: Run tests
      run: ninja -C build test

    - name: Run CPU-X
      run: |
        error=0
        sudo CPUX_BCLK=100 valgrind cpu-x --issue-fmt || error=1
        cat /tmp/cpu-x.log
        cat /tmp/cpu-x-daemon.log
        exit $error
